name: Webpack build

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/npm@1.0.0
        args: install

      - uses: actions/npm@1.0.0
        args: run deploy
