name: linter
on: pull_request
jobs:
  example:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run linter
        run: |
          echo "::add-matcher::.github/workflows/linter-matcher.json"
          python ./.github/workflows/linter.py
